project:
  type: website
  post-render: scripts/post-render.py
format:
  html:
    theme: flatly
    css:
    - great-docs.css
    toc: true
    toc-depth: 2
    toc-title: On this page
    shift-heading-level-by: -1
    include-in-header:
    - text: <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
website:
  page-navigation: true
  title: Xplor
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Getting Started
      href: usage.md
    - text: API Reference
      href: reference/index.qmd
  sidebar:
  - id: reference
    contents:
    - section: Classes
      contents:
      - reference/XplorModel.qmd
      - reference/VarType.qmd
    - section: Other
      contents:
      - reference/var.qmd
      - reference/mathopt.qmd
      - reference/gurobi.qmd
  page-footer:
    left: '&copy; 2025 Gabriel Robin'
quartodoc:
  parser: numpy
  package: xplor
  dir: reference
  title: API Reference
  style: pkgdown
  dynamic: true
  renderer:
    style: markdown
    table_style: description-list
  sections:
  - title: Classes
    desc: Core classes and types
    contents:
    - XplorModel
    - VarType
  - title: Other
    desc: Additional exports
    contents:
    - var
